import { MindMapNode } from '../types/MindMapNode';

const data: MindMapNode = {
  "name": "Topic 3: Bonding and Structure",
  "id": "topic3_questions",
  "summary": "Exam-style questions for Topic 3: Bonding and Structure",
  "children": [
    {
      "name": "What evidence supports the existence of ions, and how can you interpret physical properties, electron density maps, and ion migration demonstrations?",
      "id": "topic3-1",
      "summary": "Evidence for ions includes: high melting and boiling points of ionic compounds due to strong lattice energies; brittleness resulting from layers sliding and repelling like charges; conduction of electricity in molten or aqueous states due to mobile ions; electron density maps showing electron depletion around cations and accumulation around anions; and demonstrations of ion migration in U-tube experiments or on microscope slides. These observations confirm the presence of discrete charged species."
    },
    {
      "name": "How do atoms form ions by loss or gain of electrons?",
      "id": "topic3-2",
      "summary": "Ions form when neutral atoms achieve noble gas electron configurations by losing electrons to become cations (e.g., Na → Na⁺ + e⁻) or gaining electrons to become anions (e.g., Cl + e⁻ → Cl⁻). The resulting electrostatic attraction between oppositely charged ions leads to ionic bonding."
    },
    {
      "name": "How do you draw dot-and-cross diagrams to show electrons in cations and anions?",
      "id": "topic3-3",
      "summary": "Dot-and-cross diagrams represent valence electrons: use dots for one atom’s electrons and crosses for the other. For cations, show electron loss (empty valence shell) and for anions, show gained electrons to complete an octet, indicating charge outside the bracket with the overall ionic charge."
    },
    {
      "name": "How would you describe ionic crystals as giant lattices of ions?",
      "id": "topic3-4",
      "summary": "Ionic crystals consist of a three-dimensional lattice of alternating cations and anions arranged in a repeating pattern that maximizes electrostatic attractions and minimizes repulsions, forming a giant structure extending throughout the solid."
    },
    {
      "name": "What causes ionic bonding, and what is its nature?",
      "id": "topic3-5",
      "summary": "Ionic bonding arises from strong electrostatic attraction between oppositely charged ions generated by electron transfer. This bond is non-directional and extends throughout the lattice."
    },
    {
      "name": "How do ionic radius and ionic charge affect the strength of ionic bonding?",
      "id": "topic3-6",
      "summary": "Bond strength increases with higher ionic charge (greater Coulombic attraction) and decreases with larger ionic radius (greater distance between ions), according to Coulomb’s law (F ∝ q₁q₂/r²)."
    },
    {
      "name": "What trends in ionic radii occur down a group and among isoelectronic ions (e.g., N³⁻ to Al³⁺), and why?",
      "id": "topic3-7",
      "summary": "Down a group, ionic radii increase due to additional electron shells. Among isoelectronic ions, radii decrease with increasing nuclear charge (e.g., N³⁻ > O²⁻ > F⁻ > Na⁺ > Mg²⁺ > Al³⁺) as greater positive charge pulls electrons closer."
    },
    {
      "name": "What is polarisation in ionic compounds?",
      "id": "topic3-8",
      "summary": "Polarisation occurs when a cation’s electric field distorts an anion’s electron cloud, giving the bond some covalent character. Smaller, highly charged cations polarise large, highly charged anions more effectively."
    },
    {
      "name": "How do cation polarising power and anion polarisability depend on radius and charge?",
      "id": "topic3-9",
      "summary": "Cation polarising power increases with higher charge and smaller radius; anion polarisability increases with larger radius and higher charge, since diffuse electron clouds are easier to distort."
    },
    {
      "name": "What evidences support covalent bonding, and how is it defined based on electron sharing?",
      "id": "topic3-10",
      "summary": "Covalent bonding is the strong electrostatic attraction between nuclei and shared electron pairs, evidenced by low melting/boiling points of simple molecules and electron density maps showing electron concentration between atoms."
    },
    {
      "name": "How do you draw dot-and-cross diagrams for covalent substances, including single, double, triple, and dative bonds (e.g., Al₂Cl₆, NH₄⁺)?",
      "id": "topic3-11",
      "summary": "Use dots and crosses to represent valence electrons from each atom. Single bonds share one pair, double bonds two pairs, triple bonds three pairs, and dative bonds are indicated by an arrow from the donor to the acceptor atom, completing octets."
    },
    {
      "name": "Describe the structures and applications of the giant carbon lattices: graphite, diamond, and graphene.",
      "id": "topic3-12",
      "summary": "Diamond: each C atom tetrahedrally bonded to four others in a 3D network; extremely hard, high melting point, electrical insulator. Graphite: layers of hexagonal carbon sheets with delocalised electrons between layers; conducts electricity, lubricates. Graphene: single layer of graphite; exceptional strength, conductivity."
    },
    {
      "name": "What is electronegativity, and how does it apply to atoms in a covalent bond?",
      "id": "topic3-13",
      "summary": "Electronegativity is an atom’s tendency to attract bonding electrons; differences in electronegativity determine bond polarity and ionic versus covalent character."
    },
    {
      "name": "How do you explain the continuum from covalent to ionic bonding using electronegativity differences?",
      "id": "topic3-14",
      "summary": "Small electronegativity differences yield non-polar covalent bonds, moderate differences yield polar covalent bonds, large differences (>~1.7 Pauling) result in ionic bonding, forming a spectrum of bond character."
    },
    {
      "name": "How can you distinguish between polar bonds and polar molecules, and predict molecular polarity?",
      "id": "topic3-15",
      "summary": "A bond is polar if electrons are unequally shared; a molecule is polar if bond dipoles do not symmetrically cancel. Use molecular geometry to assess net dipole moment."
    },
    {
      "name": "What principles of electron-pair repulsion theory are used to predict the shapes of simple molecules and ions?",
      "id": "topic3-16",
      "summary": "Electron-pair repulsion theory (VSEPR) states that electron pairs around a central atom arrange to minimise repulsion, with lone pairs exerting greater repulsion than bonding pairs."
    },
    {
      "name": "Define bond length and bond angle.",
      "id": "topic3-17",
      "summary": "Bond length is the distance between the nuclei of two bonded atoms. Bond angle is the angle between two bonds at a central atom."
    },
    {
      "name": "What are the shapes and bond angles in BeCl₂, BCl₃, CH₄, NH₃, NH₄⁺, H₂O, CO₂, PCl₅ (g), SF₆, and C₂H₄?",
      "id": "topic3-18",
      "summary": "BeCl₂: linear (180°); BCl₃: trigonal planar (120°); CH₄: tetrahedral (109.5°); NH₃: trigonal pyramidal (~107°); NH₄⁺: tetrahedral (109.5°); H₂O: bent (~104.5°); CO₂: linear (180°); PCl₅: trigonal bipyramidal (axial 90°, equatorial 120°); SF₆: octahedral (90°); C₂H₄: planar around double bond (120°)."
    },
    {
      "name": "How do you apply VSEPR theory to predict the shapes and bond angles in molecules and ions analogous to those above?",
      "id": "topic3-19",
      "summary": "Count bonding and lone pairs, determine electron pair geometry, then adjust for lone pair repulsion to find molecular shape and bond angles, using appropriate steric number."
    },
    {
      "name": "Describe the structure of metals in terms of giant lattices of metal ions and delocalised electrons.",
      "id": "topic3-20",
      "summary": "Metals consist of a lattice of positive metal ions surrounded by a 'sea' of delocalised valence electrons that move freely throughout the structure."
    },
    {
      "name": "What is metallic bonding, and how do metal ions and delocalised electrons interact?",
      "id": "topic3-21",
      "summary": "Metallic bonding is the strong electrostatic attraction between positively charged metal ions and the sea of delocalised electrons, holding the lattice together."
    },
    {
      "name": "How do the lattice and electron model explain metals’ electrical conductivity and high melting points?",
      "id": "topic3-22",
      "summary": "Delocalised electrons allow metals to conduct electricity and heat. Strong electrostatic attractions between ions and electrons give metals high melting and boiling points."
    }
  ]
};

export default data;
