'use client';
import React, { useEffect, useRef, useState } from 'react';

import * as d3 from 'd3';

// Define TypeScript interfaces for our data structure
interface MindmapNode {
  name: string;
  id: string; // Unique identifier for the node
  summary?: string; // Optional detailed description
  children?: MindmapNode[];
}

// Define the structure returned by d3.hierarchy
interface HierarchyNode extends d3.HierarchyNode<MindmapNode> {}

// Define the structure for links generated by d3
interface HierarchyLink extends d3.HierarchyLink<MindmapNode> {}

// Define the main component
const IntermolecularForcesMindmap: React.FC = () => {
  const svgRef = useRef<SVGSVGElement>(null);
  const [infoContent, setInfoContent] = useState<string>('');
  const [activeNode, setActiveNode] = useState<string | null>(null);
  const [zoom, setZoom] = useState<number>(1);
  const zoomRef = useRef<d3.ZoomBehavior<SVGSVGElement, unknown> | null>(null);

  // Zoom control handlers
  const handleZoomIn = () => {
    if (svgRef.current && zoomRef.current) {
      d3.select(svgRef.current)
        .transition()
        .duration(300)
        .call(zoomRef.current.scaleBy, 1.3);
    }
  };

  const handleZoomOut = () => {
    if (svgRef.current && zoomRef.current) {
      d3.select(svgRef.current)
        .transition()
        .duration(300)
        .call(zoomRef.current.scaleBy, 0.7);
    }
  };

  const handleReset = () => {
    if (svgRef.current && zoomRef.current) {
      const width = 1200; 
      const height = 800;
      d3.select(svgRef.current)
        .transition()
        .duration(500)
        .call(
          zoomRef.current.transform,
          d3.zoomIdentity.translate(width / 2, height / 2).scale(0.8)
        );
    }
  };

  // Define the data structure for the mindmap
  const data: MindmapNode = {
    name: "Intermolecular Forces",
    id: "root",
    children: [
      {
        name: "Intermolecular Interactions",
        id: "interactions",
        children: [
          {
            name: "Types of Interactions",
            id: "interaction-types",
            children: [
              {
                name: "Non-bonded Interactions",
                id: "non-bonded",
                summary: "Non-bonded interactions are considerably weaker than covalent and polar covalent bonds. They occur between molecules and include London forces (dispersion forces) and permanent dipole interactions. They are critical in determining physical and chemical properties of molecules. \n\n**Definition & Origin:** Present in all molecules (both polar and nonpolar). Arise from instantaneous (temporary) dipoles caused by fluctuations in electron distribution, inducing dipoles in neighboring molecules. First proposed by Fritz London in 1930. \n**Key Factors:** Number of Electrons/Molecular Size (More electrons → stronger LDF due to increased polarizability). Surface Area/Shape (Larger contact area → stronger LDF). \n**Example Trend:** Noble gases boiling points increase down the group due to increasing electrons and stronger LDF.",
                children: [
                  {
                    name: "London Dispersion Forces",
                    id: "london-forces",
                    summary: "London forces (also called dispersion forces) result from instantaneous dipole-induced dipole interactions. They exist between all types of molecules, whether non-polar or polar. London forces increase with the number of electrons and molecular size/shape, providing more contact points between molecules. This affects boiling points, as seen in noble gases (He: 4.3K, Rn: 211K) and halogens. \n\n**Definition & Origin:** Present in all molecules (both polar and nonpolar). Arise from instantaneous (temporary) dipoles caused by fluctuations in electron distribution, inducing dipoles in neighboring molecules. First proposed by Fritz London in 1930. \n**Key Factors:** Number of Electrons/Molecular Size (More electrons → stronger LDF due to increased polarizability). Surface Area/Shape (Larger contact area → stronger LDF). \n**Example Trend:** Noble gases boiling points increase down the group due to increasing electrons and stronger LDF.",
                  },
                  {
                    name: "Permanent Dipoles",
                    id: "permanent-dipoles",
                    summary: "Permanent dipole interactions occur when molecules with permanent dipoles align and interact. However, unlike induced dipoles, these are not always favorably aligned in liquids due to random molecular movement, making their average interaction weaker than instantaneous dipole-induced dipole interactions. \n\n**Details:** Intermolecular interactions that stem from the presence of a permanent polarity in the molecule.",
                  },
                  {
                    name: "Induced Dipoles",
                    id: "induced-dipoles",
                    summary: "When a molecule's electron density fluctuates, it creates an instantaneous dipole. This dipole can induce a dipole in neighboring molecules, creating a favorable interaction. These induced dipoles are always aligned in a way that maximizes attraction, and occur very rapidly compared to molecular movement. \n\n**Interaction with Permanent Dipoles:** A permanent dipole in one molecule can induce a dipole in a nearby nonpolar molecule. Often grouped together under ‘dipole–dipole forces’ (includes permanent dipole–dipole and permanent dipole–induced dipole interactions).",
                  }
                ]
              },
              {
                name: "Hydrogen Bonds",
                id: "hydrogen-bonds",
                summary: "Hydrogen bonding is a special type of intermolecular interaction occurring when hydrogen is bonded to small, highly electronegative atoms (O, N, or F). It involves partial bond formation between the hydrogen atom and a lone pair on another atom. Hydrogen bonds are directional with bond angles often close to 180°. Though hydrogen bonds are at least four times weaker than covalent bonds, they're strong enough to significantly affect physical properties. \n\n**Definition:** A strong type of dipole–dipole interaction occurring when H is bonded to a highly electronegative atom (N, O, or F) and is simultaneously attracted to another electronegative atom. \n**Relative Strength:** Stronger than typical dipole–dipole interactions but weaker than covalent bonds. \n**Electronegativity & Bond Strength:** Generally increases in the order: N–H…N < N–H…O < O–H…O < F–H…F.",
                children: [
                  {
                    name: "H bonded to N, O, or F",
                    id: "h-bond-elements",
                    summary: "Hydrogen bonding is most significant when hydrogen is bonded to highly electronegative atoms - oxygen, nitrogen, and fluorine. The strength of hydrogen bonds increases with electronegativity: H₂S < NH₃ < H₂O < HF. Compounds containing -O-H, -N-H, and F-H groups can form intermolecular hydrogen bonds. \n\n**Details:** Emphasizes the most electronegative scenario for hydrogen bonding (e.g., H–F, H–O, H–N). Hydrogen bonds involving fluorine are often the strongest.",
                  },
                  {
                    name: "Significant in water, DNA, proteins",
                    id: "h-bond-significance",
                    summary: "Hydrogen bonding is crucial in biological systems. The physical properties of water, which covers about two-thirds of Earth's surface, are largely due to its extensive hydrogen bonding network. DNA's double helix structure is held together by hydrogen bonds. These bonds are strong enough to maintain structural integrity but weak enough to allow DNA to unwind for replication. Proteins and other biomolecules also depend on hydrogen bonding for their structure and function. \n\n**Biological Importance:** Water (high boiling point, surface tension, solvent power). DNA (double helix strands held together, allowing separation). Proteins (intramolecular H-bonds stabilize secondary, tertiary, quaternary structures).",
                  }
                ]
              }
            ]
          },
          {
            name: "Factors Affecting Strength",
            id: "strength-factors",
            summary: "The strength of intermolecular forces depends on several factors that determine how molecules interact with each other.",
            children: [
              {
                name: "Number of Electrons",
                id: "electron-number",
                summary: "As molecular mass increases, the number of electrons per molecule increases, enhancing instantaneous and induced dipoles. This creates stronger London forces, resulting in higher boiling points, as seen in alkanes and noble gases. The trend of increasing boiling points correlates directly with increasing electron count. \n\n**Effect:** Directly affects London dispersion forces. More electrons → greater polarizability → stronger dispersion forces → higher boiling points.",
              },
              {
                name: "Molecular Size",
                id: "molecular-size",
                summary: "Larger molecules have more contact points between adjacent molecules, increasing the overall intermolecular attraction. Each point of contact contributes to the London forces, making larger molecules have stronger overall attraction forces and higher boiling points.",
              },
              {
                name: "Molecular Shape",
                id: "molecular-shape",
                summary: "The shape of molecules affects how well they can pack together. Unbranched alkanes pack closely with points of contact all along the chain, resulting in stronger intermolecular forces. Branched alkanes cannot pack as efficiently, leading to fewer contact points, weaker intermolecular forces, and lower boiling points (e.g., pentane: 309K, 2,2-dimethylpropane: 283K). \n\n**Effect:** Extended, elongated shapes offer more surface contact → stronger LDF. Branched shapes reduce contact → weaker LDF, lower boiling points.",
              },
              {
                name: "Polarity",
                id: "polarity",
                summary: "Polar molecules have permanent dipoles that create additional intermolecular forces beyond London forces. This results in higher boiling points compared to non-polar molecules with similar numbers of electrons. For example, alcohols have much higher boiling points than alkanes with similar electron counts due to hydrogen bonding (methanol: 338K vs. ethane: 184K). \n\n**Effect:** Dipole–Dipole Forces (More polar molecules have stronger attractions). Solubility ('Like Dissolves Like': Polar dissolves polar/ionic; Nonpolar dissolves nonpolar).",
              }
            ]
          }
        ]
      },
      {
        name: "Intermolecular Interactions and Physical Properties",
        id: "interactions-properties",
        summary: "Intermolecular forces significantly influence the physical properties of substances including boiling and melting points, solubility, and other characteristics.",
        children: [
          {
            name: "Trends in Alkanes",
            id: "alkanes-trends",
            summary: "Alkanes show clear trends in physical properties related to intermolecular forces:",
            children: [
              {
                name: "Boiling point increases with chain length",
                id: "alkane-boiling-point",
                summary: "In unbranched alkanes (CₙH₂ₙ₊₂), boiling temperatures increase with molecular mass. For example, methane (CH₄): -164°C, octane (C₈H₁₈): 125°C. This occurs because: 1) More electrons per molecule create stronger instantaneous and induced dipoles, and 2) Longer carbon chains provide more contact points between molecules, enhancing overall London forces. \n\n**Details:** As chain length increases, boiling point rises (stronger LDF). Branched alkanes have lower boiling points than straight-chain isomers (less surface contact).",
              },
              {
                name: "Volatility decreases with chain length",
                id: "alkane-volatility",
                summary: "Volatility decreases as chain length increases in the alkane series. Smaller alkanes like methane and ethane are gases at room temperature, while larger ones like octane are liquids. The enthalpy of vaporization (energy required to separate molecules) increases with chain length, reflecting stronger intermolecular attractions in larger molecules. \n\n**Reason:** Due to increasing London dispersion forces in longer carbon chains. Higher IMFs reduce volatility.",
              }
            ]
          },
          {
            name: "Trends in Alcohols",
            id: "alcohols-trends",
            summary: "Alcohols (compounds with -OH groups) show distinctive physical properties due to hydrogen bonding:",
            children: [
              {
                name: "Higher boiling points than similar alkanes",
                id: "alcohol-vs-alkane",
                summary: "Alcohols have significantly higher boiling points than alkanes with similar molecular mass. For example, methanol (CH₃OH, 18 electrons): 338K vs. ethane (C₂H₆, 18 electrons): 184K. This difference occurs because alcohols form hydrogen bonds while alkanes only have London forces. The hydrogen bonding provides an additional attractive force, requiring more energy to separate the molecules. \n\n**Reason:** Alcohols (R–OH) can hydrogen bond through the –OH group, significantly raising boiling points. As carbon chain grows, LDF also become important, but H-bonding remains dominant factor.",
              },
              {
                name: "Hydrogen bonding",
                id: "alcohol-h-bonding",
                summary: "Hydrogen bonding in alcohols occurs between the -O-H group of one molecule and the oxygen atom of another. For short-chain alcohols like methanol and ethanol, hydrogen bonding is the predominant intermolecular force. However, as chain length increases, London forces become increasingly important. In longer-chain alcohols, hydrogen bonding contributes proportionally less to the total intermolecular forces (ethanol: 59%, pentanol: 45%).",
              }
            ]
          },
          {
            name: "Solubility",
            id: "solubility",
            summary: "Solubility depends on the intermolecular forces between solute and solvent molecules. For dissolution to occur: 1) Solute particles must separate and become surrounded by solvent, and 2) The attraction between solute and solvent must be strong enough to overcome solute-solute and solvent-solvent attractions.",
            children: [
              {
                name: "Water dissolves ionic compounds",
                id: "water-ionic",
                summary: "Water is effective at dissolving ionic compounds due to ion-dipole interactions. The δ- ends of water molecules attract positive ions (cations), while the δ+ ends attract negative ions (anions). This hydration process provides enough energy to overcome the ionic lattice energy, allowing dissolution of many ionic compounds like sodium chloride. \n\n**Mechanism:** Ion–Dipole Interactions: Polar water molecules surround and stabilize individual ions (e.g., Na⁺, Cl⁻), pulling them from the crystal lattice.",
              },
              {
                name: "Water dissolves some polar covalent compounds",
                id: "water-polar",
                summary: "Water dissolves polar molecules that can form hydrogen bonds with water molecules. Small alcohols like methanol and ethanol are completely miscible with water because the -OH groups form hydrogen bonds with water molecules, similar in strength to water-water hydrogen bonds. As the hydrocarbon chain length increases in alcohols, solubility decreases as the London forces between alcohol molecules become dominant. \n\n**Reason:** 'Like Dissolves Like': Polar water dissolves polar/ionic substances. Hydrogen Bonding: Water forms H-bonds with molecules having O–H, N–H, or F–H groups, increasing solubility.",
              },
              {
                name: "Non-aqueous solvents for non-polar compounds",
                id: "non-aqueous",
                summary: "Non-polar compounds dissolve best in non-polar solvents, following the principle that 'like dissolves like.' For example, alkanes dissolve in other alkanes, and non-polar substances like oils and fats dissolve in non-polar solvents like hexane but not in water. Halogenoalkanes are poorly soluble in water but dissolve well in ethanol, which is why reactions of halogenoalkanes are often conducted in aqueous ethanol. \n\n**Reason:** Nonpolar solvents (e.g., hexane) dissolve nonpolar compounds via London dispersion forces. 'Like dissolves like' applies.",
              }
            ]
          },
          {
            name: "Melting and Boiling Points",
            id: "melting-boiling",
            summary: "Melting and boiling points depend on the energy required to overcome intermolecular forces. Substances with strong intermolecular forces require more energy and thus have higher melting and boiling points. Hydrogen bonding in water leads to its unusually high boiling point (100°C) compared to H₂S (-60°C), despite H₂S having more electrons. \n\n**Principle:** Stronger IMFs → higher melting/boiling points. \n**Example:** Water’s high boiling point (100°C) due to H-bonding.",
          },
          {
            name: "Water's Properties",
            id: "water-properties",
            summary: "Water's unique properties stem from extensive hydrogen bonding:",
            children: [
              {
                name: "High melting/boiling points",
                id: "water-high-bp",
                summary: "Compared to other hydrides like H₂S, H₂Se, and H₂Te, water has significantly higher melting (0°C) and boiling points (100°C) due to its strong hydrogen bonds. \n\n**Reason:** Strong IMFs (H-bonding) require more energy to overcome.",
              },
              {
                name: "Density anomaly",
                id: "water-density",
                summary: "Solid water (ice) is less dense than liquid water. This occurs because hydrogen bonding creates an open tetrahedral structure in ice. As ice melts, this structure collapses, allowing molecules to pack more closely. Water reaches maximum density at 4°C.",
              },
              {
                name: "High surface tension",
                id: "water-surface-tension",
                summary: "Water has high surface tension because hydrogen bonds create a strong network at the surface, requiring significant energy to break. \n\n**Reason:** Hydrogen bonds create a 'skin' on the water surface.",
              },
              {
                name: "High specific heat capacity",
                id: "water-specific-heat",
                summary: "Water has a high specific heat capacity, meaning it takes a lot of energy to raise its temperature. This is because energy is absorbed to break hydrogen bonds before increasing kinetic energy. \n\n**Reason:** Extensive H-bonding means more energy is needed to raise temperature.",
              },
              {
                name: "Solvent properties",
                id: "water-solvent",
                summary: "Water's polarity and ability to form hydrogen bonds make it an excellent solvent for many ionic and polar substances.",
              }
            ]
          },
          {
            name: "Dissolving Ionic Compounds in Water",
            id: "dissolving-ionic",
            summary: "When ionic compounds dissolve in water, the ions are separated from the crystal lattice and become surrounded by water molecules in a process called hydration. The negative ends of water molecules orient toward positive ions, while the positive ends orient toward negative ions. The energy released during hydration (hydration energy) helps overcome the lattice energy holding the ionic solid together. \n\n**Mechanism:** Ion–Dipole Interactions: Polar water molecules surround and stabilize individual ions (e.g., Na⁺, Cl⁻), pulling them from the crystal lattice.",
          },
          {
            name: "Life without water (antifreeze proteins)",
            id: "antifreeze-proteins",
            summary: "Some organisms have evolved antifreeze proteins to survive in freezing environments. These proteins bind to the surface of developing ice crystals, preventing further growth by forcing the ice to form curved surfaces between the bound proteins. This allows organisms like arctic fish to survive in water below the normal freezing point without ice formation damaging their cells and tissues.",
          }
        ]
      }
    ]
  };

  // Use effect hook for D3 logic
  useEffect(() => {
    if (!svgRef.current) return;

    const width = 1200;
    const height = 800;
    const radius = Math.min(width, height) / 2 * 0.9;

    // Select the SVG element and clear previous content
    const svg = d3.select(svgRef.current)
      .attr('width', width)
      .attr('height', height)
      .attr('viewBox', [-width / 2, -height / 2, width, height])
      .style('font', '10px sans-serif');
    svg.selectAll("*").remove(); // Clear previous render

    // Create root group centered in SVG
    const g = svg.append('g');

    // Create tree layout generator
    const treeLayout = d3.tree<MindmapNode>()
      .size([2 * Math.PI, radius])
      .separation((a, b) => (a.parent == b.parent ? 1 : 2) / a.depth);

    // Create hierarchy from data
    const root = d3.hierarchy(data);

    // Generate the tree layout
    const treeData = treeLayout(root);

    // Add links between nodes
    const link = g.append("g")
      .attr("fill", "none")
      .attr("stroke", "#ccc") // Lighter link color
      .attr("stroke-opacity", 0.7)
      .attr("stroke-width", 1.5)
      .selectAll("path")
      .data(treeData.links())
      .join("path")
      .attr("d", d3.linkRadial<any, d3.HierarchyPointNode<MindmapNode>>() // Type hint for node data
        .angle(node => node.x) // Access angle from the node object
        .radius(node => node.y)); // Access radius from the node object

    // Add nodes with colors based on depth
    const colorScale = d3.scaleOrdinal<string, string>() // Domain type string (depth as string)
      .domain(["0", "1", "2", "3", "4"]) // Max depth assumed 4
      .range(["#4299E1", "#48BB78", "#F6AD55", "#F56565", "#9F7AEA"]);

    // Add nodes
    const node = g.append("g")
      .attr("stroke-linejoin", "round")
      .attr("stroke-width", 3)
      .selectAll("g")
      .data(treeData.descendants())
      .join("g")
      .attr("transform", d => `
        rotate(${(d.x * 180 / Math.PI - 90)}) 
        translate(${d.y},0)
      `);

    // Add node circles WITH HOVER EFFECT (reinstated) 
    node.append("circle")
      .attr("fill", (d: any) => colorScale(d.depth.toString())) // Use string depth for colorScale
      .attr("r", d => d.data.id === "root" ? 10 : 6)
      .style("cursor", "pointer")
      .on("click", (event: MouseEvent, d: any) => {
        setActiveNode(d.data.id);
        setInfoContent(d.data.summary || `${d.data.name} - No summary available.`);
      })
      .on("mouseover", (event: MouseEvent, d: any) => {
        // Cast currentTarget to SVGCircleElement for d3.select
        d3.select(event.currentTarget as SVGCircleElement).attr('r', (d: any) => d.data.id === 'root' ? 12 : 8).attr('stroke', 'black'); // Enlarge and highlight on hover
      })
      .on("mouseout", (event: MouseEvent, d: any) => {
          // Cast currentTarget to SVGCircleElement for d3.select
          d3.select(event.currentTarget as SVGCircleElement).attr('r', (d: any) => d.data.id === 'root' ? 10 : 6).attr('stroke', null); // Revert size and highlight
      });

    // Add node text labels - Rotate First, Then Translate
    const text = node.append("text")
      // Remove x attribute, position is handled by translate
      .attr("x", null)
      .attr("transform", (d: any) => {
        const inverseRotation = -(d.x * 180 / Math.PI - 90);
        const horizontalOffset = d.x < Math.PI ? 8 : -8;
        // Apply rotation around origin (0,0) first, then translate horizontally
        return `rotate(${inverseRotation}) translate(${horizontalOffset}, 0)`; 
      })
      .attr("dy", "0.31em") // Vertical alignment
      .attr("text-anchor", (d: any) => d.x < Math.PI ? "start" : "end") // Anchor based on left/right side
      .attr("fill", (d: any) => colorScale(d.depth.toString())) // Use string depth for colorScale
      .style("font-size", "10px")
      .style("font-weight", "bold")
      .style("pointer-events", "none") // Avoid interfering with circle click
      .text((d: any) => d.data.name);
      
    // Set initial content
    setInfoContent("Click on any node to see detailed information about that topic.");

    // Setup zoom behavior
    const zoomBehavior = d3.zoom<SVGSVGElement, unknown>()
      .scaleExtent([0.3, 3])
      .on("zoom", (event: d3.D3ZoomEvent<SVGSVGElement, unknown>) => {
        g.attr("transform", event.transform.toString());
        setZoom(event.transform.k);
      });

    // Store zoom behavior in ref for external control
    zoomRef.current = zoomBehavior;

    // Apply zoom behavior to SVG
    svg.call(zoomBehavior)
      .on("dblclick.zoom", null); // Disable double-click zoom

    // Initialize with a slight zoom out
    const initialTransform = d3.zoomIdentity.translate(0, 0).scale(0.8); // Centered by viewBox
    svg.call(zoomBehavior.transform, initialTransform);

  }, []); // Empty dependency array: run only once on mount

  // Find the name of the active node for the title
  const findNodeName = (nodeId: string | null, nodeData: MindmapNode): string | null => {
    if (!nodeId) return null;
    if (nodeData.id === nodeId) return nodeData.name;
    if (nodeData.children) {
      for (const child of nodeData.children) {
        const found = findNodeName(nodeId, child);
        if (found) return found;
      }
    }
    return null;
  };
  const activeNodeName = findNodeName(activeNode, data);

  return (
    <div className="flex flex-col w-full h-screen bg-gray-800 text-white"> {/* Full height, dark theme */}
      <div className="p-2 bg-gray-700 text-center sticky top-0 z-10">
        <h1 className="text-xl font-semibold">Chapter 7: Intermolecular Forces</h1>
      </div>
      
      <div className="flex-grow flex flex-col md:flex-row overflow-hidden"> {/* Use flex-grow */} 
        {/* Mindmap Area */} 
        <div className="w-full md:w-2/3 h-2/3 md:h-full overflow-hidden relative bg-gray-900"> {/* Darker background for SVG */}
          <svg ref={svgRef} className="w-full h-full"></svg>
        </div>
        
        {/* Information Panel */} 
        <div className="w-full md:w-1/3 h-1/3 md:h-full p-4 bg-gray-700 overflow-y-auto border-t md:border-t-0 md:border-l border-gray-600">
          <div className="bg-gray-800 rounded-lg shadow p-4">
            <h2 className="text-lg font-semibold mb-2">
              {activeNodeName || "Topic Information"} {/* Show active node name */} 
            </h2>
            <div className="prose prose-invert max-w-none text-gray-300"> {/* Dark theme prose */} 
              {infoContent ? (
                <p>{infoContent}</p>
              ) : (
                <p>Click on a node in the mindmap to see detailed information.</p>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default IntermolecularForcesMindmap;